services:
  samba-ad:
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: samba4-ad
    hostname: dc1
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - debian_samba_etc:/etc/samba
      - debian_samba_lib:/var/lib/samba
      - debian_samba_logs:/var/log/samba
    tty: true
    stdin_open: true

volumes:
  samba_etc:
  samba_lib:
  samba_logs:
