name: Workflow to Build and Push Multi-platform

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.github/workflows/**'
      - '!.gitignore'
      - '!README.md'
      - '!LICENSE'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Build and push Fedora
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: jarbelix/samba4-addc:fedora
          platforms: linux/amd64, linux/arm64
          push: true

      - name: Build and push Debian
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./debian/Dockerfile
          tags: jarbelix/samba4-addc:debian
          platforms: linux/amd64, linux/arm64
          push: true
