name: Workflow to Build and Push Multi Plataform
# Reference: https://docs.docker.com/build/ci/github-actions/multi-platform/

# Run workflow on every push to main branch
# Reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.github/workflows/**'
      - '!.gitignore'
      - '!README.md'
      - '!LICENSE'
  schedule:
    - cron: '0 0 * * *' # Example: Runs daily at midnight UTC
  workflow_dispatch:  # Example: Runs workflow manually

# Your workflows jobs
# Reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:

  build-and-push:
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     dockerfile: [ ./Dockerfile ]  #, ./debian/Dockerfile, ./ubuntu/Dockerfile]
    #     image: [jarbelix/samba4-addc-fedora ] #, jarbelix/samba4-addc-debian, jarbelix/samba4-addc-ubuntu]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ matrix.image }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: jarbelix/samba4-addc-fedora:v1,jarbelix/samba4-addc-fedora:latest
          platforms: linux/amd64, linux/arm64
          push: true
          # file: ${{ matrix.dockerfile }}
          # tags: ${{ steps.meta.outputs.tags }}
