# Your workflow name
name: Workflow para Build e Push

# Run workflow on every push to main branch
# Reference: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.github/workflows/**'
      - '!.gitignore'
      - '!README.md'

# Your workflows jobs
# Reference: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:

      - name: Login no Docker Hub
        run: docker login ${{ vars.DOCKER_REGISTRY }} -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Logout do Docker Hub
        run: docker logout ${{ vars.DOCKER_REGISTRY }}

      - name: Checkout do repositório de código
        uses: actions/checkout@v4

      - name: Listar arquivos
        run: |
          ls -lat

      - name: Build & push Docker - linux/amd64
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: jarbelix/samba4-addc-fedora
            tags: v1,latest
            dockerfile: Dockerfile
            registry: ${{ vars.DOCKER_REGISTRY }}
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Executar commandos linux
        run: |
          AGORA=`date +%Y/%m/%d-%H:%M:%S`
          echo "date ===> $AGORA"
          echo "======================================================"
          cat /etc/os-release
          echo "======================================================"
          docker images